# Generated by Django 4.2.6 on 2023-11-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('curso', models.TextField(max_length=255)),
                ('disciplina', models.TextField(max_length=255)),
                ('ano', models.IntegerField(max_length=255)),
            ],
        ),
    ]
